import { useEffect, useState } from "react";
import { ArrowLeft, Plus, Pencil, Trash2, Camera, CarFront, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../contexts/useAuth";
import TransportRepository from "../../database/repositories/TransportRepository";
import { imageFileToDataUrl } from "../../utils/imageData";
import "./Transport.css";

const fresh = () => ({ name: "", vehicleType: "Car", vehicleNumber: "", ownership: "own", pricingMode: "perKm", ratePerKm: "", packageAmount: "", driverName: "", driverPhone: "", additionalPhone: "", driverBetaPerDay: "" });
export default function Transport() {
  const navigate = useNavigate(); const { user } = useAuth();
  const [rows, setRows] = useState([]); const [form, setForm] = useState(null); const [error, setError] = useState("");
  const load = async () => setRows(await TransportRepository.list(user?.id));
  useEffect(() => { load(); }, [user?.id]);
  const field = (label, key, type = "text") => <label>{label}<input type={type} value={form[key] ?? ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>;
  const save = async (e) => { e.preventDefault(); try { await TransportRepository.save(form, user?.id); setForm(null); setError(""); await load(); } catch (err) { setError(err.message); } };
  const takePhoto = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { setForm({ ...form, photo: await imageFileToDataUrl(file, 1000, 0.78) }); } catch (err) { setError(err.message); } event.target.value = ""; };
  return <main className="transport-page"><header><button onClick={() => navigate(-1)} aria-label="Back"><ArrowLeft /></button><div className="transport-page-title"><h1>Saved Vehicles</h1><p>Save vehicle and driver details to reuse when setting up a trip.</p></div><button onClick={() => setForm(fresh())} aria-label="Add vehicle"><Plus /></button></header>
    {form && <form className="transport-form" onSubmit={save}><h2>{form.id ? "Edit transport" : "Add transport"}</h2>{field("Transport name *", "name")}{field("Vehicle type", "vehicleType")}{field("Vehicle number", "vehicleNumber")}<label>Ownership<select value={form.ownership} onChange={(e) => setForm({ ...form, ownership: e.target.value })}><option value="own">Private / Own vehicle</option><option value="rented">Rented vehicle</option></select></label><label>Pricing mode<select value={form.pricingMode} onChange={(e) => setForm({ ...form, pricingMode: e.target.value })}><option value="perKm">Rate per km</option><option value="package">Package price</option></select></label>{form.pricingMode === "perKm" ? field("Default ₹/km", "ratePerKm", "number") : field("Package amount ₹", "packageAmount", "number")}{field("Driver name", "driverName")}{field("Driver mobile", "driverPhone", "tel")}{field("Additional mobile", "additionalPhone", "tel")}{field("Driver beta per day ₹", "driverBetaPerDay", "number")}<label className="vehicle-photo-button"><Camera size={18} />{form.photo ? "Change vehicle photo" : "Take vehicle photo"}<input type="file" accept="image/*" capture="environment" onChange={takePhoto} /></label>{form.photo && <div className="vehicle-photo-preview"><img src={form.photo} alt="Vehicle" /><button type="button" onClick={() => setForm({ ...form, photo: null })}><X size={16} /></button></div>}{error && <p className="transport-error">{error}</p>}<button type="button" onClick={() => setForm(null)}>Cancel</button><button type="submit">Save</button></form>}
    {!rows.length && !form && <div className="transport-empty"><CarFront size={36}/><h2>No Saved Vehicles Yet</h2><p>Add a vehicle once, then reuse its details when you set up future trips.</p><button onClick={() => setForm(fresh())}><Plus size={17}/> Add Vehicle</button></div>}{rows.map((row) => <article className="transport-row" key={row.id}>{row.photo ? <img className="transport-thumb" src={row.photo} alt="" /> : <span className="transport-thumb-placeholder"><CarFront /></span>}<div><strong>{row.name}</strong><span>{row.vehicleType} · {row.ownership === "rented" ? "Rented" : "Own vehicle"}{row.vehicleNumber ? ` · ${row.vehicleNumber}` : ""}</span><span>{row.pricingMode === "package" ? `Package ₹${row.packageAmount || 0}` : `₹${row.ratePerKm || 0}/km`}</span></div><button onClick={() => setForm({ ...fresh(), ...row })} aria-label="Edit"><Pencil size={18} /></button><button onClick={async () => { if (window.confirm("Delete this saved vehicle? Existing trips keep their snapshots.")) { await TransportRepository.remove(row.id); await load(); } }} aria-label="Delete"><Trash2 size={18} /></button></article>)}
  </main>;
}
